# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        name: UISESSION

# +-----------------------------------------------------
# |         SPRING CONFIG
# +-----------------------------------------------------
spring:
  application:
    name: ml-challenge
  profiles:
    active: "@activatedProperties@"
  jackson:
    serialization:
      INDENT_OUTPUT: false