SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `dbcomunication` ;

CREATE SCHEMA IF NOT EXISTS `dbcomunication` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;

USE `dbcomunication` ;

CREATE TABLE IF NOT EXISTS TBL_MESSAGE (
    ID_MESSAGE     INT(11),
    CODE_MESSAGE   VARCHAR(512),
    NAME_SATELLITE VARCHAR(60),
    DISTANCE       FLOAT(10,7),
    MESSAGE        VARCHAR(512),
    CORRELATION_ID VARCHAR(50)
) ENGINE = InnoDB;

ALTER TABLE TBL_MESSAGE ADD CONSTRAINT PK_MSG PRIMARY KEY (ID_MESSAGE);
ALTER TABLE TBL_MESSAGE ADD FULLTEXT (CODE_MESSAGE, MESSAGE);