# +-----------------------------------------------------
# |         SPRING DATASOURCE CONFIG
# +-----------------------------------------------------
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2://mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa